# Создание пользователя
# checked ok
- hosts: init_root
  become: yes
  vars_files:
    - s_media_secrets.yaml

  vars:
    postgresql_version: 14
  tasks:

  - name: Creating user "{{ uusername }}" with admin access
    user: 
      name: "{{ uusername }}"
      password: "{{ upassword | password_hash('sha512') }}"
      shell: /bin/bash
      groups: "sudo"
      append: yes
