---
- name: Deploy front-end s_media (Vue.js)
  hosts: no_root
  become: yes  # Если нужны права root
  vars:
    git_repo: "https://github.com/SergueiMoscow/s_media_front"
    app_directory: "/var/www/s_media_front"
    node_version: "20.x"
  vars_files:
    - s_media_secrets.yaml

  tasks:

    # - name: Установить зависимости для сборки
    #   apt:
    #     name: ["git", "npm"]
    #     state: latest

    - name: Клонировать репозиторий с исходным кодом Vue.js
      git:
        repo: "{{ git_repo }}"
        dest: "{{ app_directory }}"
        clone: yes
        force: yes

    - name: Копирование конфига .env (Front-end)
      template:
        src: templates/env_front_end
        dest: /var/www/s_media_front/.env


    - name: Установка PM2 глобально
      npm:
        name: pm2
        global: yes
      become: yes

    - name: Установить зависимости проекта
      npm:
        path: "{{ app_directory }}"

    - name: Собрать Vue.js проект
      npm:
        path: "{{ app_directory }}"
        ci: yes # Больше подходит для продакшен сборки

    - name: запуск Vue.js проекта с помощью PM2
      shell: pm2 start npm --name "s_media_front" -- run build
      args:
        chdir: "{{ app_directory }}"
