- hosts: no_root
  become: yes
  vars_files:
    - s_media_secrets.yaml

  tasks:

  - name: Get stuff from git
    git:
      repo: https://github.com/SergueiMoscow/s_media_api.git
      dest: "{{ backend }}"

  - name: Get Poetry virtualenv path
    shell: ~/.local/bin/poetry env info -p
    args:
      chdir: "{{ backend }}"
    register: poetry_env_path
    changed_when: false

  - name: Run django migrate (API)
    community.general.django_manage:
      command: migrate
      project_path: "{{ backend }}"
      settings: "django_app.settings"
      virtualenv: "{{ poetry_env_path.stdout }}"
    notify: restart uvicorn

  handlers:
    - name: restart uvicorn
      systemd:
        name: s_media_api
        state: restarted
